services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 38080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_PASSWORD=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
    command: start-dev
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - "./compose/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "pg_data:/var/lib/postgresql/data"
volumes:
  pg_data:
