services:
  backend:
    build: ./compose/backend
    ports:
      - 35000:5000
    environment:
      - JWKS_URL=http://proxy/realms/master/protocol/openid-connect/certs
    volumes:
      - "./compose/backend:/code:ro"
    restart: always
    command: 
      - /bin/sh
      - -c 
      - python -u app.py
  proxy:
    build: ./compose/proxy
    ports:
      - 38080:80
      - 38443:443
    restart: always
    depends_on:
      - keycloak16
      - keycloak25
      - backend
    environment:
      - KC16_HOST=keycloak16.local
      - KC25_HOST=keycloak25.local
      - BACKEND_HOST=backend.local
      - PROXY_HOST=proxy.local
      - PROXY_TLS_PORT=38443
      - GLOBAL_KC_JWKS_URL=http://keycloak16:8080/auth/realms/master/protocol/openid-connect/certs
      - LOCAL_KC_JWKS_URL=http://keycloak25:8080/realms/master/protocol/openid-connect/certs
      - CHECK_INTERVAL_SECONDS=5
      - CONNECTION_TIMEOUT_SECONDS=20
      - PROXY_MODE=auto
    volumes:
      - ./compose/backend/static:/var/www/backend:ro
      - ./compose/nginx/templates/keycloak16.conf.template:/etc/nginx/templates/keycloak16.conf.template:ro
      - ./compose/nginx/templates/keycloak25.conf.template:/etc/nginx/templates/keycloak25.conf.template:ro
      - ./compose/nginx/templates/backend.conf.template:/etc/nginx/templates/backend.conf.template:ro
      - ./compose/nginx/tls/kc16/cert.pem:/etc/nginx/tls/keycloak16.local/cert.pem:ro
      - ./compose/nginx/tls/kc16/key.pem:/etc/nginx/tls/keycloak16.local/key.pem:ro
      - ./compose/nginx/tls/kc25/cert.pem:/etc/nginx/tls/keycloak25.local/cert.pem:ro
      - ./compose/nginx/tls/kc25/key.pem:/etc/nginx/tls/keycloak25.local/key.pem:ro
      - ./compose/nginx/tls/backend/cert.pem:/etc/nginx/tls/backend.local/cert.pem:ro
      - ./compose/nginx/tls/backend/key.pem:/etc/nginx/tls/backend.local/key.pem:ro
      - ./compose/nginx/tls/proxy/key.pem:/etc/nginx/tls/proxy.local/key.pem:ro
      - ./compose/nginx/tls/proxy/cert.pem:/etc/nginx/tls/proxy.local/cert.pem:ro
  nginx:
    image: nginx:1.27.4
    ports:
      - 39080:80
      - 39443:443
    restart: always
    depends_on:
      - keycloak16
      - keycloak25
      - backend
    environment:
      - KC16_HOST=keycloak16.local
      - KC25_HOST=keycloak25.local
      - BACKEND_HOST=backend.local
      - PROXY_TLS_PORT=39443
    volumes:
      - ./compose/backend/static:/var/www/backend:ro
      - ./compose/nginx/templates/keycloak16.conf.template:/etc/nginx/templates/keycloak16.conf.template:ro
      - ./compose/nginx/templates/keycloak25.conf.template:/etc/nginx/templates/keycloak25.conf.template:ro
      - ./compose/nginx/templates/backend.conf.template:/etc/nginx/templates/backend.conf.template:ro
      - ./compose/nginx/tls/kc16/cert.pem:/etc/nginx/tls/keycloak16.local/cert.pem:ro
      - ./compose/nginx/tls/kc16/key.pem:/etc/nginx/tls/keycloak16.local/key.pem:ro
      - ./compose/nginx/tls/kc25/cert.pem:/etc/nginx/tls/keycloak25.local/cert.pem:ro
      - ./compose/nginx/tls/kc25/key.pem:/etc/nginx/tls/keycloak25.local/key.pem:ro
      - ./compose/nginx/tls/backend/cert.pem:/etc/nginx/tls/backend.local/cert.pem:ro
      - ./compose/nginx/tls/backend/key.pem:/etc/nginx/tls/backend.local/key.pem:ro
      - ./compose/nginx/tls/proxy/key.pem:/etc/nginx/tls/proxy.local/key.pem:ro
      - ./compose/nginx/tls/proxy/cert.pem:/etc/nginx/tls/proxy.local/cert.pem:ro
  keycloak16:
    image: quay.io/keycloak/keycloak:16.1.1
    ports:
      - 38016:8080
      - 38787:8787
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_PASSWORD=keycloak
      - DB_USER=keycloak
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak16
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
      - KC_PROXY=edge
      - DEBUG=true
      - JAVA_OPTS_APPEND="-Dkeycloak.profile.feature.token_exchange=enabled"
      # - JAVA_OPTS_APPEND="-Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.impersonation=enabled -Dkeycloak.profile.feature.admin_fine_grained=enabled"
    restart: always
    volumes:
      - ./compose/keycloak16/startup-scripts/keycloak.cli:/opt/jboss/startup-scripts/keycloak.cli:ro
      - ./compose/keycloak16/deployments:/opt/jboss/keycloak/standalone/deployments:rw
      - ./compose/keycloak16/bin/standalone.sh:/opt/jboss/keycloak/bin/standalone.sh
    depends_on:
      - postgres
  keycloak25:
    image: quay.io/keycloak/keycloak:25.0.4
    ports:
      - 38025:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_PASSWORD=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak25
    command: ["start-dev", "--proxy-headers=xforwarded", "--http-enabled=true", "--hostname-strict=false"]
    restart: always
    entrypoint: ["/opt/keycloak/bin/kc.sh"]
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - "./compose/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "pg_data:/var/lib/postgresql/data"
volumes:
  pg_data:
