services:
  keycloak16:
    image: quay.io/keycloak/keycloak:16.1.0
    ports:
      - 38016:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_PASSWORD=keycloak
      - DB_USER=keycloak
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak16
    restart: always
    depends_on:
      - postgres
  keycloak24:
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 38024:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_PASSWORD=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak24
    command: start-dev
    restart: always
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3
    ports:
      - 25432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - "./compose/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "pg_data:/var/lib/postgresql/data"
volumes:
  pg_data:
